== About


=== Javascript on the EV3

*Provide a simple and powerful way to program on the EV3 with Javascript*.

* Gnikrap is *straightforward to use*.
* Gnikrap can be *used on a computer or a tablet*, in fact any device that have a modern browser (HTML5 compatible).
* *Javascript*, is currently one of the more popular scripting language


=== Empower your device' sensors

*Gnikrap give the opportunity to use the tablet sensors in the same way as if this is sensor directly linked to the EV3 device*. 
The list of XSensors (for eXternal Sensors) available right now is:

* xTouch: A *24 touch tactile screen* that enable to remotely pilot a robot in a simple way 
  (see <<The xTouch XSensor>> for more details).
* XGyro: *Use the gyroscope of your mobile device* (eg. tablet) in order to control a robot 
  (see <<The xGyro XSensor>> for more details).
* xVideo: *Use the webcam* of any device (tablet, computer) in order *to track objects* (see <<The xVideo XSensor>> for more details) and make 
  your robot react to the environment.
* xGeo: *Use the *GPS* of your device (eg. tablet or smartphone) in order to send GPS coordinate to the EV3 (see <<The xGeo XSensor>> for more details).


[NOTE]
====
Other XSensors that could be envisaged in the future: 

- xSound sensor, 
- other video algorithms for the xVideo sensor, 
- other modes for the xTouch sensor
====


=== Full documentation available

You are at the right place to evaluate it ! Just have look to see if it's ok for you :-)


=== Why don't use Gnikrap

Gnikrap is nice, but you're not sure... Here are some element that can make you use another tool/library to program with the EV3 :

* If you need a full featured API (*access to non-Lego sensors*, navigation/orientation API, etc.) or if *speed 
execution* (you plan to implement complex/CPU-intensive algorithm) is one of you key criteria, consider using a library like http://www.lejos.org/[leJOS] or http://www.monobrick.dk/[MonoBrick]. +
_Note:_ Gnikrap is internally based on leJOS.
* If you need *graphical programming* tools, consider using the software provided by Lego


[NOTE]
====
To sum up, the two main objective of Gnikrap are: 

* Give a middle path between the Lego visual programming environment and the "complex" development environment (and associated knowledge) needed by lejos or MonoBrick.
* Give access to the some of the sensors of your tablet/laptop/smartphone in order to leverage the EV3 possibilities and add more fun to your creations.
====
