== About


=== Javascript on the EV3

*Provide a simple and powerful way to program on the EV3 with Javascript*.

* Gnikrap is *straightforward to use*.
* Gnikrap can be *used on a computer or a tablet*, in fact any device that have a modern browser (HTML5 compatible).
* *Javascript*, is currently one of the more popular scripting language
* Code autocompletion (since 0.5.0) make writing JavaScript really more easier.


=== Scratch-like on the EV3

*Since version 0.5.0 a https://scratch.mit.edu/[Scratch]-like editor has been added to Gnikrap in order to write program simply.* This feature has been added mainly to provide to kids that are often familiar with Scratch-like applications/games a simple way to start before moving towards JavaScript programming.

* A Scratch-like editor to program the EV3 brick simply (even more simple than the programing environment provided with the Mindstrom).
* *Generation of clean JavaScript code* from any Scratch-like program: This provide an easy way to JavaScript programming.

[NOTE]
====
The graphical editor is based on the https://developers.google.com/blockly/[Blockly] library.
====


=== Empower your device' sensors

*Gnikrap give the opportunity to use the tablet sensors in the same way as if this is sensor directly linked to the EV3 device*. 
The list of XSensors (for eXternal Sensors) available right now is:

* xTouch: A *24 touch tactile screen* that enable to remotely pilot a robot in a simple way 
  (see <<The xTouch XSensor>> for more details).
* XGyro: *Use the gyroscope of your mobile device* (eg. tablet) in order to control a robot 
  (see <<The xGyro XSensor>> for more details).
* xVideo: *Use the webcam* of any device (tablet, computer) in order *to track objects* (see <<The xVideo XSensor>> for more details) and make 
  your robot react to the environment.
* xGeo: *Use the GPS* of your device (eg. tablet or smartphone) in order to send GPS coordinate to the EV3 (see <<The xGeo XSensor>> for more details).

[NOTE]
====
XSensors are available only in JavaScript mode.
====


=== Full documentation available

You are at the right place to evaluate it ! Just have look to see if it's ok for you :-)


=== Why don't use Gnikrap

Gnikrap is nice, but you're not sure... Here are some element that can make you use another tool/library to program with the EV3 :

* If you need a *full featured API* (*access to non-Lego sensors*, navigation/orientation API, etc.) consider using a library like http://www.lejos.org/[leJOS] or http://www.monobrick.dk/[MonoBrick].
* If *speed execution* (you plan to implement complex/CPU-intensive algorithm) consider using a library like http://www.lejos.org/[leJOS] or http://www.monobrick.dk/[MonoBrick].

_Note:_ Gnikrap is internally based on leJOS.


[NOTE]
====
To sum up, the three main objective of Gnikrap are: 

* Give a really simple way to program EV3 in a Scratch-like graphical user interface.
* Give a middle path between the Lego visual programming environment and the _"complex"_ development environment (and associated knowledge) needed by lejos or MonoBrick.
* Give access to the some of the sensors of your tablet/laptop/smartphone in order to leverage the EV3 possibilities and add more fun to your creations.
====
