== How to install

=== Prerequesite: Install leJOS

Before installing Gnikrap, you need to have a working leJOS firmware. Moreover, a network (either Wifi or bluetooth should have been configured.

Lejos installation::
. Download and install http://www.lejos.org/[leJOS] as described on the page: http://sourceforge.net/p/lejos/wiki/Installing%20leJOS/[Installing leJOS
. Configure a network link between your computer and the EV3:
** Either with Wifi, see http://sourceforge.net/p/lejos/wiki/Configuring%20Wifi/[Configuring Wifi]
** Either with bluetooth PAN, see http://sourceforge.net/p/lejos/wiki/Configuring%20Bluetooth%20PAN/[Pairing (from the PC)]


=== Install for Windows users

You're lucky, you benefit of a full automated install.

** Download the Gnikrap distribution for Windows https://github.com/jbenech/gnikrap/releases[here]
** Unzip the distribution and launch the program `insall_on_ev3.exe`. This program will ask you the IP address of the EV3 and will install
leJOS on the EV3. +
_Note:_ The IP address is displayed on the screen while leJOS is installed and running.

That's all ! You can now run Gnikrap, see TODO


=== Install for non Windows users

** Download the Gnikrap distribution for all operating systems (install-all) https://github.com/jbenech/gnikrap/releases[here]
** Upload the tar.gz file on the brick. You can upload on the brick by using the a software that implement the SCP protocol (eg on Windows: http://winscp.net/eng/download.php[WinSCP])
** Once uploaded, you need to connect (either with telnet or ssh) to the EV3. (eg on Windows, http://the.earth.li/~sgtatham/putty/latest/x86/putty.zip[Putty]) +
   _Note:_ The login to use is "root" and there is no password.
** Once connected, decompress the tar.gz file with a command like: `tar -xzf gnikrap-install-all-<Version>.tar.gz` (Replace <Version> with the right version according to the file you have)
** Go to the folder just created with a command like: `cd gnikrap-install-all-<Version>` (Here again, <Version> has to be replaced with the right version)
** Last but not least, launch the Gnikrap install with a command like: `./install.sh` +
   Note: If Gnikrap has already been installed, the program can prompt you to uninstall the previous installed version.


=== Launch Gnikrap   

** With the leJOS menu go to 'Program' TODO # click on the middle button.
** On the list, select Gnikrap and click again on the middle button.
** Select 'run' TODO (this is the default) and click again on the middle button.
** Gnikrap will be launched (it take a some long seconds).
** Once Gnikrap was launched, you can connect with a browser. +
   _Note:_ In order to come back to the leJOS menu, you have to stop Gnikrap by using the `Gnikrap` menu in the any browser connected to the brick.
