==== A robot controlled with the xGyro sensor

See the video of this sample: https://www.youtube.com/watch?feature=player_embedded&v=IDihLF-AEEY[Gnikrap xSensor: 2 axis Gyroscope for Lego Mindstorm EV3]


The aim of this sample is to pilot a robot with the gyroscope of a device.

The robot is to be made of:

* 1 motor for a left wheel (or caterpillar) 
* 1 motor for the right wheel (or caterpillar) 

[NOTE]
====
You also need a device (computer, tablet or smartphone) connected to the EV3 (and running Gnikrap) with a 2 axis gyroscopic sensor.
====

[source,javascript]
----
///////////////////////////////////////////////////////////////////////////////
// Note: Please adjust the port to what is physically connected on your brick.
///////////////////////////////////////////////////////////////////////////////

// Initialization // <1>
var left = ev3.getBrick().getLargeMotor("D");
var right = ev3.getBrick().getLargeMotor("A");
var xGyro = ev3.getXSensor("xGyro");


// Define a function that activate (or not) one motor with the given percentage (positive or negative) // <2>
function activateMotor(motor, powerInPercent) {
    if(Math.abs(powerInPercent) < 10) { // // <3>
        motor.stop();
    } else if(powerInPercent > 10) {
        motor.setSpeedPercent(powerInPercent);
        motor.forward();
    } else if(powerInPercent < 10) {
        motor.setSpeedPercent(-powerInPercent);
        motor.backward();
    }
}


// Main loop - This is the main program // <4>
while(ev3.isOk()) {
    var gyro = xGyro.getValue();

    if(gyro.isStarted()) { // // <5>
        var x = gyro.getX().getAngle();
        var y = gyro.getY().getAngle();
        
        var leftPower = 0;
        if(x > 10) {
            leftPower = -(Math.min(Math.round(2*x), 100)); // Back (-) => Forward (+)
        } else if(x < -10) {
            leftPower = Math.min(Math.round(2*-x), 100);
        }
        var rightPower = leftPower;
        
        if(y > 10) {
            if(leftPower >= 0) {
                leftPower += Math.min(Math.round(y), 50);
                if(rightPower == 0) {
                    rightPower = -leftPower;
                }
            } else {
                leftPower -= Math.min(Math.round(y), 50);
            }
        } else if(y < -10) {
            if(rightPower >= 0) {
                rightPower += Math.min(Math.round(-y), 50);
                if(leftPower == 0) {
                    leftPower = -rightPower;
                }
            } else {
                rightPower -= Math.min(Math.round(-y), 50);
            }
        }
        
        activateMotor(left, leftPower);
        activateMotor(right, rightPower);
    } else { // // <6>
        activateMotor(left, 0);
        activateMotor(right, 0);
    }
}

// Finalization
// None (motors will be automatically stopped)
----
<1> Here we retrieve all ev3 objects needed in the main loop. +
    *Caution*: The port has to match with what is physically connected on the brick
<2> We define a function that enable to make a motor, go forward, go backward or stop according to a power value 
    (between -100 and 100)
<3> We use the standard Javascript `Math` object in order to make our computations (See http://www.w3schools.com/js/js_math.asp)
<4> The "program" itself. Two main cases: 
<5> 1st case: xSensor is on, we compute the left motor and right motor power according to the x and y angle returned by the xGyro sensor 
    (see below for more details on the motor power computation).
<6> 2nd case: xSensor is off, we ensure that the motor are stopped.


// Workaround - Comment otherwise only the table was displayed ?!


Motor power computation::
* The x axis is used to control the forward/backward direction.
* The y axis is used to control the left/right direction.
* The motor speed is proportional to the angle. The variation is computed from 10° and 50° (which is the maximum).


[cols="^h,^,^,^", options="header"]
|===
|                | x < -10° | -10° < x < 10° | x > 10°
| y < -10°       | Go forward and left. | Move left in place, _i.e._ motor with opposite speed. | Go backward and left.
| -10° < y < 10° | Go forward (no turn). | Don't move. | Go backward (no turn).
| y > 10°        | Go forward and right. | Move right in place, _i.e._(otor with opposite speed. | Go backward and right.
|===
 