=== A robot that stay in the video

The aim of this robot is to have robot that stay in the video.

The behaviour of the robot will be quite simple: go forward and while your reach the 'border' of the video, go a bit backward, turn
and... go forward again !


The robot is to be made of:

* 1 motor for a left wheel (or caterpillar) 
* 1 motor for the right wheel (or caterpillar) 

[NOTE]
====
You also need a device with a webcam that is able to make the xVideo sensor work at a minimun framerate of 20 FPS.
====

[source,javascript]
----
///////////////////////////////////////////////////////////////////////////////
// Note: Please adjust the port to what is physically connected on your brick.
//
// For more details on this sample, please see 'A robot that stay in the video'
// in the documentation
///////////////////////////////////////////////////////////////////////////////

// Initialization  // <1>
var leftMotor = ev3.getBrick().getLargeMotor("D");
var rightMotor = ev3.getBrick().getLargeMotor("A");
var xVideo = ev3.getXSensor("xVideo");

// The margin in order to consider that we reach the border
var borderMargin = 80; 

// Function in order to check if the ev3 is near from the xSensor "vision" border // <2>
function isNearToBorder(visibleObject) {
    return (visibleObject.getX() < borderMargin) || (visibleObject.getY() < borderMargin) 
        || ((visibleObject.getX() + borderMargin) > 640) || ((visibleObject.getY() + borderMargin) > 480);
}

// Function to move backward and make a random turn // <3>
function backwardAndTurnRandomly() {
    leftMotor.rotate(-360, true);
    rightMotor.rotate(-360);
    
    var r = 180 + Math.random() * 270;
    leftMotor.rotate(r, true);
    rightMotor.rotate(-r);
}

function stopMotors() { // // <4>
    leftMotor.stop();
    rightMotor.stop();
}

// Main loop - This is the main program // <5>
while(ev3.isOk()) {
    var val = xVideo.getValue();

    if(val.isStarted()) { // <6>
        if(val.containsObject("ev3")) { // <7>
            if(isNearToBorder(val.getObject("ev3"))) {
                backwardAndTurnRandomly();
            } else {
                leftMotor.forward();
                rightMotor.forward();
            }
        } else {
            stopMotors();
            ev3.notify("I don't find the 'ev3', please select it !");
            ev3.sleep(200);
        }
    } else {
        stopMotors();
        ev3.notify("I don't see nothing, please start the xVideo sensor !");
        ev3.sleep(200);
    }
}

// Finalization
// None (motors will be automatically stopped)
----
<1> Here we retrieve all ev3 objects needed in the main loop. +
    *Caution*: The port has to match with what is physically connected on the brick
<2> We define a function that enable to known if a <<VisibleObject object>> is near the border. +
    The function returns `true` if the VisibleObject is close to the border, false otherwise.
<3> We define a function that enable the robot to change direction while it is close to the border. +
    In this function you have to notice the two different call to `rotate()`. We want both motor to run at the same time, so we
    request an immediate return of the `rotate()` function for the 1^st^ motor. +
    Another point is the use of the method `random` of the standard Javascript Math object (See http://www.w3schools.com/js/js_math.asp)
<4> Finally we define a function that stop both motors.
<5> The "program" itself.
<6> If the xSensor is on, go ahead, if off notify the user.
<7> Then we check that an 'ev3' object is currently visible, if not notify the user. +
    If visible, we go forward until the border of the video. While the border has been reached, the ev3 make a turn and then go forward again.
